version: build.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
before_build:
- ps: >-
    nuget restore


    [xml]$proj = Get-Content src/StringToExpression/StringToExpression.csproj

    $semver = $proj.Project.PropertyGroup.Version

    Set-AppveyorBuildVariable "semver" $semver

    Update-AppveyorBuild -Version "$semver-build.${env:APPVEYOR_BUILD_NUMBER}"
build:
  verbosity: minimal
artifacts:
- path: src\StringToExpression\bin\Release\StringToExpression.*.*.*.nupkg
  name: nupkg
deploy:
- provider: NuGet
  api_key:
    secure: m1xUVHMKrTgtEjKzGIjq//R7lwqz/7QUsUEHEMDULavC/UkEq3VDNrN2+KcQSn2I
  on:
    branch: master
- provider: GitHub
  release: v$(semver)
  auth_token:
    secure: gXbKvXCpJ7lATfojiHtJlVpYYeGXCsIdHTumgAqK/4rlnNApfXNTiCaUV5QoB42K
  artifact: nupkg
  on:
    branch: master